# Generated by Django 5.2.7 on 2025-11-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwJourney', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('interests', models.TextField()),
                ('goals', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LearningJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('topic', models.CharField(max_length=200)),
                ('key_learning', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='LearningEntry',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
